add.todo:
    path: /add/todo/
    methods: POST
    controller: App\Controller\ApiController::addTodo

edit.todo:
    path: /edit/todo/{id}
    methods: POST
    controller: App\Controller\ApiController::editTodo

remove.todo:
    path: /remove/todo/{id}
    methods: DELETE
    controller: App\Controller\ApiController::removeTodo

read.todo:
    path: /read/todo/
    methods: GET
    controller: App\Controller\ApiController::readTodo
#°°°°°°°°°°°°°°°°°°°°°°°°
#   LABEL
#°°°°°°°°°°°°°°°°°°°°°°°
add.label:
    path: /add/label/
    methods: POST
    controller: App\Controller\ApiController::addLabel

edit.label:
    path: /edit/label/{id}
    methods: POST
    controller: App\Controller\ApiController::editLabel

remove.label:
    path: /remove/label/{id}
    methods: DELETE
    controller: App\Controller\ApiController::removeLabel

read.label:
    path: /read/label/
    methods: GET
    controller: App\Controller\ApiController::readLabel